const cartTypes = {
  START_ADD_CART_ITEM: 'START_ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
  ADD_CART_ERROR: 'ADD_CART_ERROR',
};

export default cartTypes;
